services:
  api:
    build: ./BikeMatrix.API
    volumes:
      - ./BikeMatrix.API:/app
      - /app/bin
      - /app/obj
    ports:
      - "5000:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
  frontend:
    build: ./bikematrix.frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
