/* tslint:disable */
/* eslint-disable */
/**
 * BikeMatrix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrandDTO } from './BrandDTO';
import {
    BrandDTOFromJSON,
    BrandDTOFromJSONTyped,
    BrandDTOToJSON,
} from './BrandDTO';
import type { OwnerDTO } from './OwnerDTO';
import {
    OwnerDTOFromJSON,
    OwnerDTOFromJSONTyped,
    OwnerDTOToJSON,
} from './OwnerDTO';

/**
 * 
 * @export
 * @interface BikeUpdateDTO
 */
export interface BikeUpdateDTO {
    /**
     * 
     * @type {number}
     * @memberof BikeUpdateDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BikeUpdateDTO
     */
    model?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BikeUpdateDTO
     */
    year?: number;
    /**
     * 
     * @type {OwnerDTO}
     * @memberof BikeUpdateDTO
     */
    owner?: OwnerDTO;
    /**
     * 
     * @type {BrandDTO}
     * @memberof BikeUpdateDTO
     */
    brand?: BrandDTO;
}

/**
 * Check if a given object implements the BikeUpdateDTO interface.
 */
export function instanceOfBikeUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BikeUpdateDTOFromJSON(json: any): BikeUpdateDTO {
    return BikeUpdateDTOFromJSONTyped(json, false);
}

export function BikeUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BikeUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'owner': !exists(json, 'owner') ? undefined : OwnerDTOFromJSON(json['owner']),
        'brand': !exists(json, 'brand') ? undefined : BrandDTOFromJSON(json['brand']),
    };
}

export function BikeUpdateDTOToJSON(value?: BikeUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'model': value.model,
        'year': value.year,
        'owner': OwnerDTOToJSON(value.owner),
        'brand': BrandDTOToJSON(value.brand),
    };
}

