/* tslint:disable */
/* eslint-disable */
/**
 * BikeMatrix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandDTO
 */
export interface BrandDTO {
    /**
     * 
     * @type {string}
     * @memberof BrandDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the BrandDTO interface.
 */
export function instanceOfBrandDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrandDTOFromJSON(json: any): BrandDTO {
    return BrandDTOFromJSONTyped(json, false);
}

export function BrandDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BrandDTOToJSON(value?: BrandDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

