/* tslint:disable */
/* eslint-disable */
/**
 * BikeMatrix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OwnerDTO
 */
export interface OwnerDTO {
    /**
     * 
     * @type {string}
     * @memberof OwnerDTO
     */
    email?: string | null;
}

/**
 * Check if a given object implements the OwnerDTO interface.
 */
export function instanceOfOwnerDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OwnerDTOFromJSON(json: any): OwnerDTO {
    return OwnerDTOFromJSONTyped(json, false);
}

export function OwnerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnerDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function OwnerDTOToJSON(value?: OwnerDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

